// Generated by CoffeeScript 1.6.3
/* Configuration file - Set your Shapeways/App specific variables here*/


(function() {
  exports.SHAPEWAYS_USERNAME = process.env.SHAPEWAYS_USERNAME || '';

  exports.SHAPEWAYS_PASSWORD = process.env.SHAPEWAYS_PASSWORD || '';

  exports.SHAPEWAYS_APPLICATION_ID = process.env.SHAPEWAYS_APPLICATION_ID || '';

  exports.API_SERVER = process.env.API_SERVER || 'shapeways.com';

}).call(this);
